name: Check format

on:
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Check for initials
        run: |
          if grep -e "- [A-Z]\." -r content/publications/*/index.md -q; then
            echo "Names in author meta-data should match the name of the author in the authors folder"
            grep -e "- [A-Z]\." -r content/publications/*/index.md
            exit 1
          fi
      - name: Check folder names
        run: |
          if [ -n "$(find . -type f -name '* *')" ]
          then
            echo "Folder names should not contain spaces"
            exit 1
          fi
      - name: Check publication format
        run: |
          pip install python-frontmatter textdistance
          python scripts/check_publication_format.py
